### ISSUE TITLE
Will 1.20.1 be updated with new content simultaneously?

### ISSUE THREAD

**Issue by Kyukoo** [Eroxen/Catenary-datapack#1]
Just as the title says, I am playing 1.20.1 and hope that the mods for version 1.20.1 can be updated in sync with the current content of version 1.21. The new zipline mechanism is so cool, and I really love it...
So, is there a possibility for 1.20.1 to still be updated? If not, that's also okay. I just wanted to say that many people here like me are looking forward to it. I hope this question won't trouble you too much... You've made a great mod.

My apologies, my English is not very good; if the expression is terrible, it's my fault.😢

**Comment by Eroxen** [comment]
Hi, thank you for the kind words! Unfortunately I will not be updating the pack for 1.20.1. I keep my packs supporting older versions if they are compatible, but since 1.21 had very large changes this is not possible.
